config/routes.rb
Rails.application.routes.draw do
  resources :cities
  get 'welcome/index'
  resources :suppliers
  resources :service_providers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/service_provider.rb
class ServiceProvider < ApplicationRecord
  belongs_to :city
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:city_name, :state)
    end
end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
  before_action :set_service_provider, only: %i[ show edit update destroy ]

  # GET /service_providers or /service_providers.json
  def index
    @service_providers = ServiceProvider.all
  end

  # GET /service_providers/1 or /service_providers/1.json
  def show
  end

  # GET /service_providers/new
  def new
    @service_provider = ServiceProvider.new
  end

  # GET /service_providers/1/edit
  def edit
  end

  # POST /service_providers or /service_providers.json
  def create
    @service_provider = ServiceProvider.new(service_provider_params)

    respond_to do |format|
      if @service_provider.save
        format.html { redirect_to service_provider_url(@service_provider), notice: "Service provider was successfully created." }
        format.json { render :show, status: :created, location: @service_provider }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_providers/1 or /service_providers/1.json
  def update
    respond_to do |format|
      if @service_provider.update(service_provider_params)
        format.html { redirect_to service_provider_url(@service_provider), notice: "Service provider was successfully updated." }
        format.json { render :show, status: :ok, location: @service_provider }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_providers/1 or /service_providers/1.json
  def destroy
    @service_provider.destroy

    respond_to do |format|
      format.html { redirect_to service_providers_url, notice: "Service provider was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_provider
      @service_provider = ServiceProvider.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_provider_params
      params.require(:service_provider).permit(:person, :activity, :city_id, :phone_number_1, :phone_number_2, :obs)
    end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[ show edit update destroy ]

  # GET /suppliers or /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1 or /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers or /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to supplier_url(@supplier), notice: "Supplier was successfully created." }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1 or /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to supplier_url(@supplier), notice: "Supplier was successfully updated." }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1 or /suppliers/1.json
  def destroy
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: "Supplier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_params
      params.require(:supplier).permit(:company, :responsible, :activity, :city_id, :commission, :email, :phone_number_1, :phone_number_2, :address, :obs)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/_city.html.erb
<div id="<%= dom_id city %>">
  <p>
    <strong>City name:</strong>
    <%= city.city_name %>
  </p>

  <p>
    <strong>State:</strong>
    <%= city.state %>
  </p>

</div>

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :city_name, style: "display: block" %>
    <%= form.text_field :city_name %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Show this city", @city %> |
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cities</h1>

<div id="cities">
  <% @cities.each do |city| %>
    <%= render city %>
    <p>
      <%= link_to "Show this city", city %>
    </p>
  <% end %>
</div>

<%= link_to "New city", new_city_path %>
<%= link_to 'Voltar', root_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @city %>

<div>
  <%= link_to "Edit this city", edit_city_path(@city) %> |
  <%= link_to "Back to cities", cities_path %>

  <%= button_to "Destroy this city", @city, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marqduo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/service_providers/_form.html.erb
<%= form_with(model: service_provider) do |form| %>
  <% if service_provider.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service_provider.errors.count, "error") %> prohibited this service_provider from being saved:</h2>

      <ul>
        <% service_provider.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :person, style: "display: block" %>
    <%= form.text_field :person %>
  </div>

  <div>
    <%= form.label :activity, style: "display: block" %>
    <%= form.text_field :activity %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.select("city_id", City.all.collect { |c| [ c.city_name, c.id ] }, { include_blank: true })%>
  </div>

  <div>
    <%= form.label :phone_number_1, style: "display: block" %>
    <%= form.number_field :phone_number_1 %>
  </div>

  <div>
    <%= form.label :phone_number_2, style: "display: block" %>
    <%= form.text_field :phone_number_2 %>
  </div>

  <div>
    <%= form.label :obs, style: "display: block" %>
    <%= form.text_area :obs %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/service_providers/_service_provider.html.erb
<div id="<%= dom_id service_provider %>">
  <p>
    <strong>Person:</strong>
    <%= service_provider.person %>
  </p>

  <p>
    <strong>Activity:</strong>
    <%= service_provider.activity %>
  </p>

  <p>
    <strong>City:</strong>
    <%= service_provider.city.city_name %>
  </p>

  <p>
    <strong>Phone number 1:</strong>
    <%= service_provider.phone_number_1 %>
  </p>

  <p>
    <strong>Phone number 2:</strong>
    <%= service_provider.phone_number_2 %>
  </p>

  <p>
    <strong>Obs:</strong>
    <%= service_provider.obs %>
  </p>

</div>

app/views/service_providers/edit.html.erb
<h1>Editing service provider</h1>

<%= render "form", service_provider: @service_provider %>

<br>

<div>
  <%= link_to "Show this service provider", @service_provider %> |
  <%= link_to "Back to service providers", service_providers_path %>
</div>

app/views/service_providers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Service providers</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Activity</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_providers.each do |provider| %>
      <tr>
        <td><%= provider.person %></td>
        <td><%= provider.activity %></td>
        <td><%= provider.city.city_name %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_service_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New service provider", new_service_provider_path %>
<%= link_to 'Voltar', root_path %>

app/views/service_providers/new.html.erb
<h1>New service provider</h1>

<%= render "form", service_provider: @service_provider %>

<br>

<div>
  <%= link_to "Back to service providers", service_providers_path %>
</div>

app/views/service_providers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service_provider %>

<div>
  <%= link_to "Edit this service provider", edit_service_provider_path(@service_provider) %> |
  <%= link_to "Back to service providers", service_providers_path %>

  <%= button_to "Destroy this service provider", @service_provider, method: :delete %>
</div>

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier) do |form| %>
  <% if supplier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
        <% supplier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :responsible, style: "display: block" %>
    <%= form.text_field :responsible %>
  </div>

  <div>
    <%= form.label :activity, style: "display: block" %>
    <%= form.text_field :activity %>
  </div>

  <div>
    <%= form.label :commission, style: "display: block" %>
    <%= form.check_box :commission %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.select("city_id", City.all.collect { |c| [ c.city_name, c.id ] }, { include_blank: true })%>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone_number_1, style: "display: block" %>
    <%= form.number_field :phone_number_1 %>
  </div>

  <div>
    <%= form.label :phone_number_2, style: "display: block" %>
    <%= form.number_field :phone_number_2 %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :obs, style: "display: block" %>
    <%= form.text_field :obs %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/suppliers/_supplier.html.erb
<div id="<%= dom_id supplier %>">
  <p>
    <strong>Company:</strong>
    <%= supplier.company %>
  </p>

  <p>
    <strong>Responsible:</strong>
    <%= supplier.responsible %>
  </p>

  <p>
    <strong>Activity:</strong>
    <%= supplier.activity %>
  </p>

  <p>
    <strong>Commission:</strong>
    <%= supplier.commission %>
  </p>

  <p>
    <strong>City:</strong>
    <%= supplier.city.city_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= supplier.email %>
  </p>

  <p>
    <strong>Phone number 1:</strong>
    <%= supplier.phone_number_1 %>
  </p>

  <p>
    <strong>Phone number 2:</strong>
    <%= supplier.phone_number_2 %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= supplier.address %>
  </p>

  <p>
    <strong>Obs:</strong>
    <%= supplier.obs %>
  </p>

</div>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render "form", supplier: @supplier %>

<br>

<div>
  <%= link_to "Show this supplier", @supplier %> |
  <%= link_to "Back to suppliers", suppliers_path %>
</div>

app/views/suppliers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Suppliers</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Responsible</th>
      <th>Activity</th>
      <th>Commission</th> 
      <th>City</th>     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.company %></td>
        <td><%= supplier.responsible %></td>
        <td><%= supplier.activity %></td>
        <td><%= supplier.commission %></td>
        <td><%= supplier.city.city_name %></td>
        <td><%= link_to 'Show', supplier %></td>
        <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
        <td><%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New supplier", new_supplier_path %>
<%= link_to 'Voltar', root_path %>

app/views/suppliers/new.html.erb
<h1>New supplier</h1>

<%= render "form", supplier: @supplier %>

<br>

<div>
  <%= link_to "Back to suppliers", suppliers_path %>
</div>

app/views/suppliers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @supplier %>

<div>
  <%= link_to "Edit this supplier", edit_supplier_path(@supplier) %> |
  <%= link_to "Back to suppliers", suppliers_path %>

  <%= button_to "Destroy this supplier", @supplier, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Marq Duo Contacts</h1><br>

<ul>
  <li>
    <%= link_to "All contacts", root_path %>
  </li>
  
  <br>

  <li>
    <%= link_to "Suppliers", suppliers_path %>
  </li>
  
  <br>

  <li>
    <%= link_to "Service providers", service_providers_path %>
  </li>
  
  <br>

  <li>
    <%= link_to "Cities", cities_path %>
  </li>
  
  <br>
  
</ul>

<%# Não utilizar <br> %>